# Generated by Django 3.0.5 on 2020-04-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bat',
            fields=[
                ('number', models.CharField(default='Номер мыши', max_length=20)),
                ('name', models.CharField(default='Имя мыши', max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=20)),
                ('ring', models.CharField(default='Номер кольца', max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batstatus', models.CharField(choices=[('Прибыл', 'Прибыла'), ('В спячке', 'В спячке'), ('Откорм', 'Откорм'), ('Выпущен', 'Выпущенна'), ('В разлеточнике', 'В разлеточнике'), ('Больна', 'Больна')], default='Прибыл', max_length=20)),
                ('batspecies', models.CharField(choices=[('Прудовая ночница', 'Прудовая ночница'), ('Водяная ночница', 'Водяная ночница'), ('Ночница Наттерера', 'Ночница Наттерера'), ('Усатая ночница', 'Усатая ночница'), ('Бурый ушан', 'Бурый ушан'), ('Ушан', 'Ушан'), ('Малая вечерница', 'Малая вечерница'), ('Рыжая вечерница', 'Рыжая вечерница'), ('Гигантская вечерница', 'Гигантская вечерница'), ('Нетопырь-карлик', 'Нетопырь-карлик'), ('Нетопырь Куля', 'Нетопырь Куля'), ('Нетопырь Натузиус', 'Нетопырь Натузиус'), ('Северный кожанок', 'Северный кожанок'), ('Двухцветный кожан', 'Двухцветный кожан'), ('Поздний кожан', 'Поздний кожан'), ('Ночница Брандта', 'Ночница Брандта')], default='Двухцветный кожан', max_length=25)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(height_field=100, upload_to='', width_field=100)),
            ],
        ),
        migrations.CreateModel(
            name='LincStatusBat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LinkBatEat',
            fields=[
                ('before_feeding', models.FloatField(default=10.5)),
                ('after_feeding', models.FloatField(default=10.5)),
                ('menu', models.CharField(choices=[('Мучник', 'Мучник'), ('Сверчки', 'Сверчки'), ('Тараканы', 'Тараканы')], default='Мучник', max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(default=1)),
                ('bat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chiroptera.Bat')),
            ],
        ),
        migrations.CreateModel(
            name='BatHealing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('bat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chiroptera.Bat')),
            ],
        ),
    ]
