# Generated by Django 3.0.5 on 2020-04-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chiroptera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bat',
            name='foto',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='images/', width_field=100),
        ),
    ]
