# Generated by Django 3.0.5 on 2020-04-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chiroptera', '0002_auto_20200420_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bat',
            name='foto',
            field=models.ImageField(default='Chiroptera.images/None/no-img.jpg', upload_to='Chiroptera.images/'),
        ),
    ]
