# Generated by Django 3.0.5 on 2020-04-19 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chiroptera', '0003_auto_20200420_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bat',
            name='batstatus',
        ),
        migrations.AlterField(
            model_name='bat',
            name='foto',
            field=models.ImageField(default='Chiroptera/images/None/no-img.jpg', upload_to='Chiroptera/images/'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batstatus', models.CharField(choices=[('Прибыл', 'Прибыла'), ('В спячке', 'В спячке'), ('Откорм', 'Откорм'), ('Выпущен', 'Выпущенна'), ('В разлеточнике', 'В разлеточнике'), ('Больна', 'Больна')], default='Прибыл', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('bat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chiroptera.Bat')),
            ],
        ),
    ]
