# Generated by Django 3.0.5 on 2020-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chiroptera', '0004_auto_20200420_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkbateat',
            name='ultraviolet',
            field=models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], default='N', max_length=20),
        ),
    ]
