# Generated by Django 3.0.5 on 2020-04-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chiroptera', '0005_linkbateat_ultraviolet'),
    ]

    operations = [
        migrations.AddField(
            model_name='lincstatusbat',
            name='bat_id',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='Chiroptera.Bat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lincstatusbat',
            name='status_id',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, to='Chiroptera.Status'),
            preserve_default=False,
        ),
    ]
